"""PPT-IR Core module exports."""

from .models import (
    PresentationIR,
    SlideIR,
    ElementIR,
    ShapeElementIR,
    TextElementIR,
    ConnectorElementIR,
    ImageElementIR,
    TableElementIR,
    GroupElementIR,
    TransformIR,
    ElementStyleIR,
    FillStyle,
    BorderStyle,
    ShadowStyle,
    GradientFill,
    GradientStop,
    TextContentIR,
    ParagraphIR,
    RunIR,
    FontIR,
)
from .converter import PPTIRConverter, ConversionReport, import_pptx, export_pptx
from .patch import PatchRecord, HistoryManager
from .svg_renderer import SVGRenderer

__all__ = [
    "PresentationIR",
    "SlideIR",
    "ElementIR",
    "ShapeElementIR",
    "TextElementIR",
    "ConnectorElementIR",
    "ImageElementIR",
    "TableElementIR",
    "GroupElementIR",
    "TransformIR",
    "ElementStyleIR",
    "FillStyle",
    "BorderStyle",
    "ShadowStyle",
    "GradientFill",
    "GradientStop",
    "TextContentIR",
    "ParagraphIR",
    "RunIR",
    "FontIR",
    "PPTIRConverter",
    "ConversionReport",
    "import_pptx",
    "export_pptx",
    "PatchRecord",
    "HistoryManager",
    "SVGRenderer",
]
