"""Phase 7 / test H: the frontend actually consumes generated IR types.

`presentation-ir.generated.ts` is the frontend source of truth for IR types; it
is generated by `backend.ir.ts_export` and enforced by CI. This test fails if the
generated file drifts, if `ppt.ts` reintroduces hand-written IR interfaces, or if
business modules stop importing the generated types.
"""

import re
from pathlib import Path

from backend.ir import ts_export

FRONTEND_SRC = Path(__file__).resolve().parents[1] / "frontend" / "src"
TYPES_DIR = FRONTEND_SRC / "types"

IR_INTERFACES = (
    "PresentationIR",
    "SlideIR",
    "ElementIR",
    "ShapeElementIR",
    "TextElementIR",
    "ConnectorElementIR",
    "ImageElementIR",
    "TableElementIR",
    "GroupElementIR",
    "FillStyle",
    "BorderStyle",
)

# Business modules that must import from the generated contract.
GENERATED_CONSUMERS = (
    FRONTEND_SRC / "store" / "usePPTStore.ts",
    FRONTEND_SRC / "components" / "PropertyPanel.tsx",
    FRONTEND_SRC / "components" / "SlideCanvas.tsx",
    FRONTEND_SRC / "components" / "SVGRendererComponent.tsx",
    FRONTEND_SRC / "editor" / "geometry" / "adapter.ts",
    TYPES_DIR / "protocol.ts",
    TYPES_DIR / "editor.ts",
)


def test_generated_types_exist_and_are_marked_autogenerated():
    assert ts_export.OUTPUT_PATH.exists()
    text = ts_export.OUTPUT_PATH.read_text(encoding="utf-8")
    assert text.startswith("// AUTO-GENERATED FILE. DO NOT EDIT.")


def test_generated_types_match_backend_models():
    assert ts_export.check_typescript(), (
        "presentation-ir.generated.ts drifted from backend models. Run "
        "`python -m backend.ir.ts_export` and commit the result."
    )


def test_generated_types_cover_core_interfaces():
    text = ts_export.OUTPUT_PATH.read_text(encoding="utf-8")
    for name in IR_INTERFACES:
        assert re.search(rf"export (interface|type) {name}\b", text), f"missing {name}"


def test_requiredness_comes_from_the_schema_not_a_hand_written_map():
    # The generator must not own a requiredness list; it reads the schema's
    # `required` array (which schema_export derives from the curated registry).
    assert not hasattr(ts_export, "REQUIRED_FIELDS")
    rendered = ts_export._render_model(
        "Demo", {"properties": {"a": {"type": "string"}, "b": {"type": "number"}}, "required": ["a"]}
    )
    assert "  a: string" in rendered
    assert "  b?: number" in rendered


def test_curated_structural_fields_are_non_optional_in_generated_types():
    text = ts_export.OUTPUT_PATH.read_text(encoding="utf-8")
    font = re.search(r"export interface FontIR \{(.*?)\}", text, re.S).group(1)
    assert not re.search(r"^\s*name\?:", font, re.M)
    assert re.search(r"^\s*bold\?:", font, re.M)


def test_ppt_barrel_reexports_generated_types_without_hand_written_ir():
    ppt = (TYPES_DIR / "ppt.ts").read_text(encoding="utf-8")
    assert "presentation-ir.generated" in ppt
    for name in IR_INTERFACES:
        assert not re.search(rf"export interface {name}\b", ppt), (
            f"hand-written IR interface {name} leaked back into ppt.ts"
        )


def test_business_modules_import_generated_types():
    missing = [
        str(path.relative_to(FRONTEND_SRC))
        for path in GENERATED_CONSUMERS
        if "presentation-ir.generated" not in path.read_text(encoding="utf-8")
    ]
    assert not missing, f"modules not importing generated IR types: {missing}"
