"""Independent Executor Subagent.

Responsible for deterministic and tool-based slide manipulation operations.
Decoupled from the orchestration graph:
- Receives clear execution tasks and canvas references.
- Executes operations with atomic transaction safety and error boundary protection.
- Reports detailed execution results and telemetry records back to the main agent.
"""

from __future__ import annotations
import inspect
import json
import logging
import uuid
from dataclasses import dataclass, field
from typing import Dict, Any, Optional, Callable, List
from ...ir.models import PresentationIR
from ...ir.patch import HistoryManager
from ..memory import AgentMemory
from ..llm import LLMClient
from .. import tools

logger = logging.getLogger(__name__)


@dataclass
class ExecutorReport:
    """Detailed report generated by the Executor Subagent for the main agent."""
    success: bool
    tool_results: List[Dict[str, Any]]
    executed_tools: List[str]
    presentation_version: int
    last_target_id: Optional[str]
    summary_message: str
    error: Optional[str] = None
    subagent_info: Dict[str, Any] = field(default_factory=lambda: {
        "subagent_name": "ExecutorSubagent",
        "context_isolated": True,
        "role": "slide_production_executor"
    })

    def to_dict(self) -> Dict[str, Any]:
        return {
            "success": self.success,
            "tool_results": self.tool_results,
            "executed_tools": self.executed_tools,
            "presentation_version": self.presentation_version,
            "last_target_id": self.last_target_id,
            "summary_message": self.summary_message,
            "error": self.error,
            "subagent_info": self.subagent_info
        }


class ExecutorSubagent:
    """Independent Executor Subagent for slide authoring operations."""

    @classmethod
    async def execute_task(
        cls,
        intent: str,
        user_query: str,
        plan_desc: str,
        pres: Optional[PresentationIR],
        history: Optional[HistoryManager] = None,
        memory: Optional[AgentMemory] = None,
        llm_client: Optional[LLMClient] = None,
        last_target_id: Optional[str] = None,
        session: Optional[Any] = None,
        on_event: Optional[Callable] = None
    ) -> ExecutorReport:
        """Executes slide generation or manipulation tools independently and reports back."""
        # 1. Broadcast lifecycle start: Main agent pauses waiting for executor subagent
        if on_event:
            await cls._safe_emit(on_event, {
                "type": "subagent_lifecycle",
                "phase": "started",
                "subagent": "ExecutorSubagent",
                "main_agent_status": "paused_waiting",
                "intent": intent,
                "text": "主 Agent 已暂停等候，独立制作执行 Subagent 介入执行图元编排与操作..."
            })

        # 2. Determine tool calls (LLM tool-calling or heuristic deterministic planner)
        has_live_llm = llm_client and getattr(llm_client, "api_key", None) and not str(llm_client.api_key).startswith("mock_") and not str(llm_client.api_key).startswith("loop_mock_")
        tool_calls: List[Dict[str, Any]] = []

        if has_live_llm:
            from ..graph import _build_llm_system_prompt
            system_prompt = _build_llm_system_prompt(pres, memory)
            # Combine plan and query into concise execution directive
            exec_prompt = f"任务意图: {intent}\n规划要求: {plan_desc}\n用户输入: {user_query}"
            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": exec_prompt}
            ]
            try:
                resp = await llm_client.chat_completion(
                    messages=messages,
                    tools=tools.schemas,
                    role="reasoning"
                )
                raw_tc = resp["choices"][0]["message"].get("tool_calls", [])
                for tc in raw_tc:
                    fn_name = tc["function"]["name"]
                    try:
                        args = json.loads(tc["function"].get("arguments", "{}"))
                    except Exception:
                        args = {}
                    tool_calls.append({"name": fn_name, "arguments": args, "id": tc.get("id", f"call_{uuid.uuid4().hex[:6]}")})
            except Exception as e:
                logger.warning(f"ExecutorSubagent LLM call error: {e}, using heuristic planner")
                from ..graph import _heuristic_tool_planner
                tool_calls = _heuristic_tool_planner(intent, user_query, pres, last_target_id=last_target_id)
            if not tool_calls:
                from ..graph import _heuristic_tool_planner
                tool_calls = _heuristic_tool_planner(intent, user_query, pres, last_target_id=last_target_id)
        else:
            from ..graph import _heuristic_tool_planner
            tool_calls = _heuristic_tool_planner(intent, user_query, pres, last_target_id=last_target_id)

        # 3. Apply tool calls with atomic transactions
        results: List[Dict[str, Any]] = []
        current_target_id = last_target_id
        executed_names: List[str] = []
        execution_error = None

        for tc in tool_calls:
            fn_name = tc["name"]
            fn_args = tc.get("arguments", {})
            executed_names.append(fn_name)

            if on_event:
                await cls._safe_emit(on_event, {
                    "type": "tool_executing",
                    "tool": fn_name,
                    "arguments": fn_args,
                    "subagent": "ExecutorSubagent"
                })

            try:
                # Handle undo / redo via session or history
                if fn_name == "undo":
                    if session and hasattr(session, "undo"):
                        patch = session.undo()
                        res = {"success": True if patch else False, "message": "已成功撤销上一步操作" if patch else "当前无历史操作可撤销"}
                    elif history and hasattr(history, "undo"):
                        patch = history.undo(pres)
                        res = {"success": True if patch else False, "message": "已成功撤销上一步操作" if patch else "当前无历史操作可撤销"}
                    else:
                        res = {"success": False, "message": "未找到可撤销的历史记录"}
                elif fn_name == "redo":
                    if session and hasattr(session, "redo"):
                        patch = session.redo()
                        res = {"success": True if patch else False, "message": "已成功重做操作" if patch else "当前无历史操作可重做"}
                    elif history and hasattr(history, "redo"):
                        patch = history.redo(pres)
                        res = {"success": True if patch else False, "message": "已成功重做操作" if patch else "当前无历史操作可重做"}
                    else:
                        res = {"success": False, "message": "未找到可重做的历史记录"}
                else:
                    # Use unified tools.execute dispatcher
                    res = tools.execute(fn_name, fn_args, pres, history)

                if isinstance(res, dict) and "element_id" in res:
                    current_target_id = res["element_id"]

                results.append({"tool": fn_name, "arguments": fn_args, "result": res})

                if on_event:
                    await cls._safe_emit(on_event, {
                        "type": "tool_completed",
                        "tool": fn_name,
                        "result": res,
                        "presentation_version": pres.version if pres else 1,
                        "subagent": "ExecutorSubagent"
                    })

                if memory:
                    memory.log_action(f"Subagent执行工具 '{fn_name}': {res.get('message', 'ok') if isinstance(res, dict) else 'ok'}")
            except Exception as e:
                logger.error(f"Error running tool {fn_name}: {e}", exc_info=True)
                execution_error = str(e)
                results.append({"tool": fn_name, "arguments": fn_args, "error": str(e)})

        tool_summary_desc = ', '.join(executed_names) if executed_names else '无具体工具'
        summary = f"执行 Subagent 已完成操作调度，成功运行: {tool_summary_desc}。"

        report = ExecutorReport(
            success=execution_error is None,
            tool_results=results,
            executed_tools=executed_names,
            presentation_version=pres.version if pres else 1,
            last_target_id=current_target_id,
            summary_message=summary,
            error=execution_error
        )

        # 4. Broadcast lifecycle completed: Main agent resumes
        if on_event:
            await cls._safe_emit(on_event, {
                "type": "subagent_lifecycle",
                "phase": "completed",
                "subagent": "ExecutorSubagent",
                "main_agent_status": "resumed",
                "executed_tools": executed_names,
                "text": f"制作执行 Subagent 汇报完成 [已执行: {tool_summary_desc}]，唤醒主 Agent 继续调度"
            })

        return report

    @staticmethod
    async def _safe_emit(on_event: Optional[Callable], data: Dict[str, Any]):
        if not on_event:
            return
        try:
            if inspect.iscoroutinefunction(on_event):
                await on_event(data)
            else:
                res = on_event(data)
                if inspect.isawaitable(res):
                    await res
        except Exception as e:
            logger.debug(f"Executor Subagent event emission ignored: {e}")
